### PR TITLE
Fix Stripe Pro-Form bug when submitting Coupon Code (use #s2p-form)

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/s2member#730

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc Review please.

**Comment by raamdev** [comment]
> This is not absolutely necessary, so if it slows you way down, just submit the PR and I'll compress.

@jaswsinc I wasn't sure which YUI Compression options you generally use when compressing, so I left this for you.

**Comment by jaswsinc** [comment]
Merged. TY!

**Comment by jaswsinc** [comment]
@raamdev Here is the script (in my dotfiles) that I use to compress JS in the s2Member repo.
https://bitbucket.org/jaswsinc/dotfiles/src/d4e0454b60f90c34ce7510aceb676eb4279dcdf3/home/.bin/compress-js?at=master&fileviewer=file-view-default

**Comment by jaswsinc** [comment]
Call it like this:

```bash
$ compress-js [script path] --old-style
```

**Pull request merged**
