### PR TITLE
PR: feature/122

### PR DESCRIPTION
**Pull request by jaswsinc**
See: websharks/s2member#122

### CODE REVIEW

**Comment by jaswsinc** [comment]
@raamdev This PR added support for some items you requested.

- Filters that allow for customization of EOT RRE (Renewal/Reminder Email) notifications.
- The ability to create custom replacement codes via a WP filter.
- Log entries for EOT RRE notification processing.

**Comment by raamdev** [comment]
@jaswsinc Awesome! Thank you. I reviewed this PR and the only thing I'd add is a filter to [the message clip in the log entry](https://github.com/websharks/s2member-pro/pull/105/files#diff-d9c373a67b45f499fbeac87040962e0aR165) in case a site owner wanted to increase that to something more than 100 characters for debugging purposes. But that's a minor thing. :smile: Nice work!

**Comment by raamdev** [comment]
↑ :grin: Thank you.

**Comment by jaswsinc** [comment]
Welcome. Thanks for the tip.

**Pull request merged**
