### PR TITLE
Mention shortcodes availability in Pro Login Widget; See: websharks/s2member#691

### PR DESCRIPTION
**Pull request by kristineds**
Mention shortcodes availability in Pro Login Widget; 

- Mentioned that shortcodes are possible in Pro Login Widget. 
- Changed field title to "Additional XHTML/PHP Code or Shortcode?"

See: websharks/s2member#691

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc Submitting Pull Request for https://github.com/websharks/s2member/issues/691

**Comment by jaswsinc** [comment]
@kristineds While we are working on this, can you change `XHTML` to just `HTML` for me please?

Also, I suggest making "Shortcode" plural "Shortcodes" instead, wrapping it with round brackets, and linking the word "Shortcodes" to an article at WordPress.org that discusses the Shortcode API in greater detail, just in case a user doesn't know what a Shortcode is.

e.g., "HTML/PHP Code (or Shortcodes)"

**Comment by kristineds** [comment]
@jaswsinc Submitting Pull Request to update text and add link for Shortcodes API. https://github.com/websharks/s2member-pro/commit/53f6c7f88828c7b96d074c5c9c91692a56ff0495

**Comment by jaswsinc** [comment]
Perfecto. Thank for doing `target="_blank"` there also.

**Pull request merged**
