### PR TITLE
Feature/122

### PR DESCRIPTION
**Pull request by jaswsinc**
See: websharks/s2member#122

### CODE REVIEW

**Comment by jaswsinc** [comment]
@raamdev Please review this class file for me when you have some time. Just looking for some help in spotting any obvious goofs here. See: https://github.com/websharks/s2member-pro/blob/feature/122/s2member-pro/includes/classes/reminders.inc.php

**Comment by jaswsinc** [comment]
Next Release Changelog:

- (s2Member Pro) **New Feature! EOT Renewal/Reminder Email Notifications:** This release adds a long-awaited feature which allows you to configure & send EOT Renewal/Reminder Email notifications to your customers; to let them know their account with you will expire soon.

  It's possible to configure one or more notifications, each with a different set of recipients, a different subject and message body. Notifications can be sent out X days before the EOT occurs, _the day_ of the EOT, or X days after the EOT has already occurred; e.g., to encourage renewals.

  See: **Dashboard → s2Member → Stripe Options → EOT Renewal/Reminder Email(s)**
  _Also works with PayPal Pro, Authorize.Net, and ClickBank._

  Props @clavaque @KTS915 @raamdev @patdumond @kristineds @pagelab @chronicelite @csexplorer17 @radven, and all of our great supporters. See [this GitHub issue](https://github.com/websharks/s2member/issues/122#issuecomment-161531763).

**Comment by jaswsinc** [comment]
### Once the RC is made available...

##### Noting that the easiest way to test this feature is as follows:

- Create a test user account and give them an EOT Time by editing their account in WordPress.

- Configure at least one EOT Renewal/Reminder Email notification that corresponds with the EOT Time that you gave the test user account that you created in the previous step.

- Now run the EOT Cron job manually by loading this blank page.
  - http://yoursite.com/?s2member_auto_eot_system_via_cron=1

---

To test again, you need to either:

- Wait up to 24 hours.
- Or, create another user and run the CRON job again manually.

_Note that each user is checked (at most), once every 24 hours. That's why it is necessary to either wait, or simply create another test user account so you can run the CRON job again manually and see what happens. If at first you don't succeed, try altering the EOT Time slightly to compensate for any date rounding that may occur during a single test run. Under normal circumstances, that won't be an issue, but for the purpose of testing (i.e., firing the CRON just once), please try offsetting the EOT time by a few hours to see if this makes any difference for you._

**Comment by raamdev** [comment]
@jaswsinc WOooooHoooo! :grinning: Great work! 

> the easiest way to test this feature is as follows

Will the log files show this activity too, i.e., when an EOT reminder email is sent out?

**Comment by raamdev** [comment]
@jaswsinc I just reviewed the new Reminders class. Nice!! There were no obvious goofs that stood out to me.

There were only two things I noticed that you might want to consider adding as part of the next release:

- I don't see a filter to programmatically alter `pro_eot_reminder_email_recipients`, `pro_eot_reminder_email_subject`, or `pro_eot_reminder_email_message` prior to sending out the email. Those might be nice filters to add to the `remind()` method.
- In the `fill_replacement_codes()` method, I see there are lots of replacement codes possible, but what if a site owner wants to use a replacement code that _doesn't_ exist there (e.g., for some content provided by another plugin, or a custom non-s2Member WordPress user field)? A filter that allows a site owner to create their own custom replacement codes would be a sweet addition.

**Comment by raamdev** [comment]
I see that PHP tags inside the fields on the UI-side are also possible, which would make customization easy. That said, it would be nice (and easy?) to add filters now that allow us to follow a common practice and make it easier for site owners who prefer to keep customizations like those in a separate file, outside of the UI.

**Comment by jaswsinc** [comment]
> Will the log files show this activity too, i.e., when an EOT reminder email is sent out?

Nope. That'd be awesome though. Love it.

**Comment by jaswsinc** [comment]
> I don't see a filter to programmatically alter pro_eot_reminder_email_recipients, pro_eot_reminder_email_subject, or pro_eot_reminder_email_message prior to sending out the email. Those might be nice filters to add to the remind() method.

Nice idea. Yep, we should add that in.

**Comment by jaswsinc** [comment]
> site owner to create their own custom replacement codes would be a sweet addition.

Cool. Yep, I like that idea also.

**Comment by csexplorer17** [comment]
I have reviewed the page we will see in s2member pro and it looks simple
enough - I don't understand about the cron job -
will we get exact details how to test it - is there a way to change a user
ending date of their membership?  I am assuming we
will update our version to s2member pro to a new version that includes this
feature - since we are still building our 1st s2mempro
service this will be a very welcome edition to test -- thank you Jason

On Thu, Dec 3, 2015 at 2:04 AM, JasWSInc <notifications@github.com> wrote:

> Next Release Changelog:
>
>    -
>
>    (s2Member Pro) *New Feature! EOT Renewal/Reminder Email Notifications:*
>    This release adds a long-awaited feature which allows you to configure &
>    send EOT Renewal/Reminder Email notifications to your customers; to let
>    them know their account with you will expire soon.
>
>    It's possible to configure one or more notifications, each with a
>    different set of recipients, a different subject and message body.
>    Notifications can be sent out X days before the EOT occurs, *the day*
>    of the EOT, or X days after the EOT has already occurred; e.g., to
>    encourage renewals.
>
>    See: *Dashboard → s2Member → Stripe Options → EOT Renewal/Reminder
>    Email(s)*
>    *Also works with PayPal Pro, Authorize.Net, and ClickBank.*
>
>    Props @clavaque <https://github.com/clavaque> @KTS915
>    <https://github.com/KTS915> @raamdev <https://github.com/raamdev>
>    @patdumond <https://github.com/patdumond> @kristineds
>    <https://github.com/kristineds> @pagelab <https://github.com/pagelab>
>    @chronicelite <https://github.com/chronicelite> @csexplorer17
>    <https://github.com/csexplorer17> @radven <https://github.com/radven>,
>    and all of our great supporters. See this GitHub issue
>    <https://github.com/websharks/s2member/issues/122#issuecomment-161531763>
>    .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/websharks/s2member-pro/pull/103#issuecomment-161577728>
> .
>



-- 
For the most fascinating information about the *crystal skulls* check out:

http://www.crystalskullexplorers.com
(the new Crystal Skull Explorer's website)

http://www.whatarecrystalskulls.com
(our Word Press site)

also get our free e-book, yes that is FREE at:
http://www.v-j-enterprises.com/free-ebook/csexplorers.html

signup for our free newsletter at:
http://www.whoisjoshuashapiro.com/newsletter-signup.htm

**Pull request merged**
